#!/bin/bash
set -e
if [ -f /output/not_mounted ]; then
    echo "You need to mount /output to actually get the binary out of the container!"
    exit 1
fi
gosu ${APP_USER}:${APP_GROUP} bash -c "cd '${APP_HOME}/go/src/github.com/joernott/semaphore' && git pull && git checkout ${SEMAPHORE_BRANCH} && git pull"
# Workaround while my changes are not back in master
cd "${APP_HOME}/go/src/github.com/joernott/semaphore"
FILES=$(find . -iname "*.go")
for FILE in ${FILES}; do
    sed -i ${FILE} -e 's|github.com/ansible-semaphore/semaphore|github.com/joernott/semaphore|g'
done
# End workaround
gosu ${APP_USER}:${APP_GROUP} bash -c "cd '${APP_HOME}/go/src/github.com/joernott/semaphore' && go get -v ./... && ./make.sh"
cp ${APP_HOME}/go/src/github.com/joernott/semaphore/cli/semaphore_linux_amd64 /output/semaphore
chmod a+rx /output/semaphore
chown ${OUTPUT_OWNER}:${OUTPUT_GROUP} /output/semaphore
